// Constantes compartilhadas para o módulo de vagas
// Listas de cursos reconhecidos pelo MEC — usadas no cadastro e edição de vagas

export const NIVEIS_ENSINO = ["Ensino Médio", "Ensino Técnico", "Ensino Superior"] as const;

export const CURSOS_TECNICO_LISTA: string[] = [
  "Técnico em Administração",
  "Técnico em Agronegócio",
  "Técnico em Agricultura",
  "Técnico em Alimentos",
  "Técnico em Análises Clínicas",
  "Técnico em Análises Químicas",
  "Técnico em Artes Gráficas",
  "Técnico em Automação Industrial",
  "Técnico em Banco de Dados",
  "Técnico em Biocombustíveis",
  "Técnico em Biotecnologia",
  "Técnico em Camareiro",
  "Técnico em Comércio",
  "Técnico em Comércio Exterior",
  "Técnico em Computação Gráfica",
  "Técnico em Comunicação Visual",
  "Técnico em Confeitaria",
  "Técnico em Contabilidade",
  "Técnico em Controle Ambiental",
  "Técnico em Cozinha",
  "Técnico em Design de Interiores",
  "Técnico em Design de Moda",
  "Técnico em Design Gráfico",
  "Técnico em Desenvolvimento de Sistemas",
  "Técnico em Edificações",
  "Técnico em Eletroeletrônica",
  "Técnico em Eletromecânica",
  "Técnico em Eletrotécnica",
  "Técnico em Enfermagem",
  "Técnico em Equipamentos Biomédicos",
  "Técnico em Estética",
  "Técnico em Eventos",
  "Técnico em Fabricação Mecânica",
  "Técnico em Farmácia",
  "Técnico em Finanças",
  "Técnico em Floricultura",
  "Técnico em Guia de Turismo",
  "Técnico em Hospedagem",
  "Técnico em Informática",
  "Técnico em Instrução de Libras",
  "Técnico em Joalheria",
  "Técnico em Logística",
  "Técnico em Manutenção Automotiva",
  "Técnico em Manutenção e Suporte em Informática",
  "Técnico em Marketing",
  "Técnico em Mecânica",
  "Técnico em Mecatrônica",
  "Técnico em Meio Ambiente",
  "Técnico em Mobile",
  "Técnico em Modelagem do Vestuário",
  "Técnico em Nutrição e Dietética",
  "Técnico em Paisagismo",
  "Técnico em Panificação",
  "Técnico em Petróleo e Gás",
  "Técnico em Produção de Áudio e Vídeo",
  "Técnico em Produção Gráfica",
  "Técnico em Programação de Jogos Digitais",
  "Técnico em Qualidade",
  "Técnico em Radiologia",
  "Técnico em Redes de Computadores",
  "Técnico em Recursos Humanos",
  "Técnico em Refrigeração e Climatização",
  "Técnico em Saúde Bucal",
  "Técnico em Secretariado",
  "Técnico em Segurança do Trabalho",
  "Técnico em Segurança Pública",
  "Técnico em Serviços de Condomínio",
  "Técnico em Serviços Jurídicos",
  "Técnico em Sistemas de Energia Renovável",
  "Técnico em Telecomunicações",
  "Técnico em Transporte Rodoviário",
  "Técnico em Turismo",
  "Técnico em Vendas",
  "Técnico em Vestuário",
  "Técnico em Veterinária",
  "Técnico em Web Design",
  "Técnico em Zootecnia",
];

export const CURSOS_SUPERIOR_LISTA: string[] = [
  "Administração",
  "Agronomia",
  "Análise e Desenvolvimento de Sistemas",
  "Arquitetura e Urbanismo",
  "Artes Visuais",
  "Biomedicina",
  "Ciência da Computação",
  "Ciência Política",
  "Ciências Atuariais",
  "Ciências Biológicas",
  "Ciências Contábeis",
  "Ciências Econômicas",
  "Ciências Sociais",
  "Comércio Exterior",
  "Comunicação Social",
  "Design de Interiores",
  "Design de Moda",
  "Design Gráfico",
  "Direito",
  "Educação Física",
  "Enfermagem",
  "Engenharia Aeronáutica",
  "Engenharia Agronômica",
  "Engenharia Ambiental",
  "Engenharia Civil",
  "Engenharia da Computação",
  "Engenharia de Alimentos",
  "Engenharia de Produção",
  "Engenharia de Software",
  "Engenharia Elétrica",
  "Engenharia Florestal",
  "Engenharia Mecânica",
  "Engenharia Química",
  "Estética e Cosmética",
  "Eventos",
  "Farmácia",
  "Filosofia",
  "Fisioterapia",
  "Fonoaudiologia",
  "Geografia",
  "Geologia",
  "Gestão Comercial",
  "Gestão da Qualidade",
  "Gestão da Tecnologia da Informação",
  "Gestão de Recursos Humanos",
  "Gestão Financeira",
  "Gestão Hospitalar",
  "Gestão Pública",
  "História",
  "Hotelaria",
  "Jornalismo",
  "Letras",
  "Logística",
  "Marketing",
  "Matemática",
  "Medicina",
  "Medicina Veterinária",
  "Meteorologia",
  "Nutrição",
  "Odontologia",
  "Pedagogia",
  "Processos Gerenciais",
  "Psicologia",
  "Publicidade e Propaganda",
  "Química",
  "Radiologia",
  "Redes de Computadores",
  "Relações Internacionais",
  "Relações Públicas",
  "Secretariado Executivo",
  "Segurança da Informação",
  "Serviço Social",
  "Sistemas de Informação",
  "Teatro",
  "Tecnologia em Alimentos",
  "Tecnologia em Estética",
  "Tecnologia em Jogos Digitais",
  "Terapia Ocupacional",
  "Turismo",
  "Zootecnia",
];

/** Parseia campo nivel ou cursoRequerido — compatível com string simples (legado) e JSON array (novo) */
export function parseMultiField(val?: string | null): string[] {
  if (!val) return [];
  try {
    const parsed = JSON.parse(val);
    if (Array.isArray(parsed)) return parsed.filter(Boolean);
  } catch {}
  return [val];
}

/** Formata array para exibição */
export function formatMultiField(arr: string[]): string {
  if (!arr.length) return "—";
  return arr.join(", ");
}
